### ISSUE TITLE
Build error: 'shared_from_this' ambiguous

### ISSUE THREAD

**Issue by stephane-caron** [PositronicsLab/Moby#5]
Hi there,

Trying out Moby, I get a build error with the latest commit (2a359a5ba10ac9f848fb461397ed723d3d45e532):

    In file included from /home/caron/Software/PositronicsLab/Moby/include/Moby/ArticulatedBody.h:18:0,
                     from /home/caron/Software/PositronicsLab/Moby/include/Moby/RCArticulatedBody.h:18,
                     from /home/caron/Software/PositronicsLab/Moby/src/SustainedUnilateralConstraintHandler.cpp:13:
    /home/caron/Software/PositronicsLab/Moby/include/Moby/Joint.h: In member function ‘Moby::JointPtr Moby::Joint::get_this()’:
    /home/caron/Software/PositronicsLab/Moby/include/Moby/Joint.h:60:69: error: reference to ‘shared_from_this’ is ambiguous
         JointPtr get_this() { return boost::dynamic_pointer_cast<Joint>(shared_from_this()); }

Full log here: http://pastebin.com/jngiSMFy ; my OS is Ubuntu 14.04.3 LTS (which packages Boost v1.54).

All the best,

**Comment by edrumwri** [comment]
Hi Stephane,

The problem you are experiencing is due to my long-awaited merging of the implicit-joints branch of Ravelin into the master branch of Ravelin. This has in turn broken the master branch of Moby (as expected).

The master branch of Moby is due for replacement with the new-Ravelin branch. This will happen in the next few months as I complete polishing. You can try out the new-Ravelin branch, which is better in every way than the master branch, but has simply not been merged (and is still not what I consider to be ready for numbered release).

Best regards,
E
